app:
  jwtExpirationInMs: '3600000'
  jwtSecret: usis
  securityValue: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: '8082'
spring:
  ldap:
    embedded:
      base-dn: dc=araproje,dc=com
      ldif: classpath:users.ldif
      port: 12345
      validation:
        enabled: false