app:
  jwtExpirationInMs: '3600000'
  jwtSecret: usis
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: '8082'
spring:
  ldap:
    embedded:
      base-dn: dc=araproje,dc=com
      ldif: classpath:users.ldif
      port: 12345
      validation:
        enabled: false
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds        
        